runtime: python311

entrypoint: gunicorn -b :$PORT app:app

instance_class: F1

handlers:
# Servir archivos estáticos raíz (importante para SEO)
- url: /favicon.ico
  static_files: static/favicon.ico
  upload: static/favicon.ico

- url: /robots.txt
  static_files: static/robots.txt
  upload: static/robots.txt

- url: /sitemap.xml
  static_files: static/sitemap.xml
  upload: static/sitemap.xml

# Esta sección sirve los archivos estáticos directamente desde la infraestructura de Google
- url: /static
  static_dir: static

- url: /.*
  script: auto

# Las variables de entorno se definen aquí.
# Cuando despliegues, puedes añadir tu ID de Google Analytics.
env_variables:
  GOOGLE_ANALYTICS_ID: "G-1PS83HXBZB"
  FLASK_ENV: "production"
  PYTHONUNBUFFERED: "True"
