runtime: python311

entrypoint: gunicorn -b :$PORT app:app

instance_class: F1

handlers:
# Esta sección sirve los archivos estáticos directamente desde la infraestructura de Google,
# lo cual es mucho más rápido que hacerlo a través de Flask.
- url: /static
  static_dir: static

- url: /.*
  script: auto

# Las variables de entorno se definen aquí.
# Cuando despliegues, puedes añadir tu ID de Google Analytics.
env_variables:
  GOOGLE_ANALYTICS_ID: "G-1PS83HXBZB"
  FLASK_ENV: "production"
  PYTHONUNBUFFERED: "True"
